# Generated by Django 5.2.1 on 2025-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_reservees', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=100)),
                ('lieu_arrivee', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('places_disponibles', models.IntegerField()),
            ],
        ),
    ]
