# Generated by Django 5.2.1 on 2025-05-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_passager', models.CharField(max_length=100)),
                ('email_passager', models.EmailField(max_length=254)),
                ('places_reservees', models.PositiveIntegerField()),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajets.trajet')),
            ],
        ),
    ]
