# Generated by Django 5.2.1 on 2025-05-29 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passager',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='places_reservees',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='Nom inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajets.trajet'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='places_disponibles',
            field=models.PositiveIntegerField(),
        ),
    ]
