# Generated by Django 5.2.1 on 2025-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0003_remove_reservation_passager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='places_souhaitees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
