# Generated by Django 5.2.1 on 2025-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tel',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='has_permis',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
    ]
